spring:
  application:
    name: service-B
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://test.tembin.com:8507/
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://test.tembin.com:8501/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true
message: service-B dev mode