# swagger2
swagger2.package: com.colossus.redis.service

spring:
  application:
    name: service-redis
  redis:
    cluster:
      nodes:
      - 192.168.0.50:7000
      - 192.168.0.50:7001
      - 192.168.0.50:7002
      - 192.168.0.53:7003
      - 192.168.0.53:7004
      - 192.168.0.53:7005
server:
  port: 8057
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8501/eureka/